version: '3.3'
services:

  mysql-db:
    image: mariadb:10.3.4
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=todos
      - MYSQL_USER=todos_user
      - MYSQL_PASSWORD=todos_password
    container_name: mysql-db
    networks:
      db:
        aliases:
          - sql

  spring-rest-service:
    build: ./spring-boot-restful-service
    depends_on:
      - mysql-db
    environment:
      - DATABASE_HOST=sql
      - DATABASE_NAME=todos
      - DATABASE_PORT=3306
      - DATABASE_USER=todos_user
      - DATABASE_PASSWORD=todos_password
    container_name: spring-rest-service
    ports:
      - 8080:8080
    networks:
      - web
      - db

  website:
    image: php:7.0-apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    networks:
      - web


networks:
  web:
  db:
